title: "The Solana Security Lab"
description: "Advanced Anatomy of Common Solana Exploits"
theme: jekyll-theme-minimal
baseurl: "/solana-security-cookbook"
url: "https://yourusername.github.io"

markdown: kramdown
highlighter: rouge
permalink: /:title/

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - examples
  - README.md
  - LICENSE

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Navigation functionality
header_pages:
  - index.md
  - about.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/card-default.png"
